### ISSUE TITLE
Remote server setup fails with --ask-pass

### ISSUE THREAD

**Issue by gmq** [roots/bedrock-ansible#206] opened 2015-05-01 16:18 UTC
Server: Linode - Ubuntu 14.04 LTS

>TASK: [mariadb | Remove the test database] ************************************
<23.92.30.251> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 23.92.30.251
<23.92.30.251> REMOTE_MODULE mysql_db name=test state=absent login_user="root" login_password=VALUE_HIDDEN
<23.92.30.251> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1430496095.36-160223569160328 && echo $HOME/.ansible/tmp/ansible-tmp-1430496095.36-160223569160328'
<23.92.30.251> PUT /var/folders/dd/sg0y898n1sl334vn_z0xs03h0000gn/T/tmp6i_95_ TO /root/.ansible/tmp/ansible-tmp-1430496095.36-160223569160328/mysql_db
<23.92.30.251> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1430496095.36-160223569160328/mysql_db; rm -rf /root/.ansible/tmp/ansible-tmp-1430496095.36-160223569160328/ >/dev/null 2>&1'
ok: [23.92.30.251] => {"changed": false, "db": "test"}

>TASK: [ssmtp | Install ssmtp] *************************************************
<23.92.30.251> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 23.92.30.251
fatal: [23.92.30.251] => {'msg': 'FAILED: timed out', 'failed': True}

>FATAL: all hosts have already failed -- aborting

After this the machine is unreachable until its rebooted.

Running ansible-playbook without --ask-pass (after uploading the keys) allows it to finish no problem.

**Comment by swalkinshaw** [comment] 2015-05-06 17:54
People occasionally get the `timed out` problem but I don't think it's anything to do with our playbooks specifically. Seems to be some Ubuntu/Ansible/connectivity issue.

Going to close this for now unless it can be reproduced.

**Closed by swalkinshaw** 2015-05-06 17:54 UTC
