### ISSUE TITLE
Re-running ansible-playbook fails on Set root user password

### ISSUE THREAD

**Issue by merchantguru** [roots/bedrock-ansible#191] opened 2015-04-27 18:51 UTC
Running `ansible-playbook -i hosts/production server.yml` a second time leads to:

```bash
TASK: [mariadb | Set root user password] ************************************** 
failed: [104.xxx.xxx.xx] => (item=Raven) => {"failed": true, "item": "Raven"}
msg: (1396, "Operation CREATE USER failed for 'root'@'raven'")
ok: [104.xxx.xxx.xx] => (item=127.0.0.1)
ok: [104.xxx.xxx.xx] => (item=::1)
ok: [104.xxx.xxx.xx] => (item=localhost)

FATAL: all hosts have already failed -- aborting
```

I need to delete the root@Raven user in MariaDB in order to proceed. Is there a way to skip this user creation on subsequent runs?

**Comment by austinpray** [comment] 2015-04-27 18:59
For debugging: what is your server setup?

**Comment by merchantguru** [comment] 2015-04-27 19:02
Stock Digital Ocean Ubuntu 14.04 x64 vmlinuz-3.13.0-43-generic 512mb. Everything else I left to bedrock-ansible.

**Comment by Foxaii** [comment] 2015-04-28 18:52
I've not been able to replicate this.  Can you let us know what version of Ansible you are using?

**Comment by merchantguru** [comment] 2015-04-28 20:16
ansible 1.9.0.1
  configured module search path = None

**Comment by retlehs** [comment] 2015-04-29 00:32
i was able to reproduce this when trying to provision a DO server as well

**Comment by merchantguru** [comment] 2015-05-04 21:16
So, my suggestion is to replace

```yaml
- name: Set root user password
  mysql_user: name=root
              ...
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
```

with

```yaml
- name: Set root user password
  mysql_user: name=root
              ...
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
```

**Comment by swalkinshaw** [comment] 2015-05-04 21:21
I'd be fine with that change but I'm curious why it fixes the issue. Also skeptical it really fixes the underlying bug across different use cases (hosts/inventory/hostnames etc).

Although it seems like `ansible_hostname` is a little strange and not documented well: https://github.com/ansible/ansible/issues/9971

So maybe we should just change this anyway and hopefully it also fixes this issue for everyone.

**Comment by merchantguru** [comment] 2015-05-04 21:21
There are 2 tasks for removing anonymous users. We could convert those to one task and include the `inventory_hostname` for good measure. 

Replace:

```yaml
- name: Delete anonymous MySQL server user for current hostname
  mysql_user: user=""
              host="{{ ansible_hostname }}"
              state=absent
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"

- name: Delete anonymous MySQL server user for localhost
  mysql_user: user=""
              state=absent
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"
```

with

```yaml
- name: Delete anonymous users from the database
  mysql_user: user=""
              host="{{ item }}"
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_root_password }}"
              state=absent
  with_items:
    - localhost
    - {{ inventory_hostname }}
    - {{ ansible_hostname }}
```

**Comment by merchantguru** [comment] 2015-05-04 21:24
Agreed! I first spent several hours trying to understand the underlying issue / fix and couldn't find a solution... until I came across someone who switched to inventory_hostname and it "just worked" for him.

**Comment by swalkinshaw** [comment] 2015-05-06 17:49
@merchantguru want to do a PR with these changes?

**Comment by swalkinshaw** [comment] 2015-05-06 19:35
Fixed by https://github.com/roots/bedrock-ansible/pull/210

**Closed by swalkinshaw** 2015-05-06 19:35 UTC

**Comment by fabianhenzler** [comment] 2015-09-04 15:31
seems like this issue occurs again
![voila_capture 2015-09-04_06-31-21_nachm](https://cloud.githubusercontent.com/assets/1168345/9687657/2e3b362a-5333-11e5-8b7c-9bb7d2141a98.png)

**Comment by louim** [comment] 2015-09-04 15:38
@fabianhenzler That's not the same problem.

There was a change made to Trellis: https://github.com/roots/trellis/pull/239 to allow users to change the root password after a first provisioning. If you provisioned your server before the change was merged, and you juste rebased you code to the latest Trellis version, you will need to do: https://github.com/roots/trellis/pull/239#issuecomment-133954971

Note that you only need to do this one time, after the provisioning complete correctly, you can remove the two lines and it will work correctly from now on. You shouldn't encounter this problem on newly provisioned server, because the `.my.cnf` will be created from the start.

**Comment by fabianhenzler** [comment] 2015-09-04 16:15
actually I don't want to change the root password - i just want to be able to set the system up and then be able to continuously update it with trellis

**Comment by louim** [comment] 2015-09-04 16:45
Yeah, this is not to change the password. The two line temporary fix is to migrate to the new way of storing the root MySQL password.

**Comment by fabianhenzler** [comment] 2015-09-05 04:46
Ok... Any recommendations on how I should save my configurations in order to be able to easily pull from the repo without having to do all the config again?

**Comment by swalkinshaw** [comment] 2022-03-29 16:46
@tomektomczuk this is a 7 year old issue for setting the root password which is a different task.

I'd suggest modifying that task to remove `no_log: true` which should help you debug. Then feel free to open a _new_ issue with more details if you there's still an issue.
